stages:
  - first
  - second
  - third

print_first:
  stage: first
  only:
    - develop
  tags:
    - build
  script:
    - echo "Hello world first!"

print_second:
  stage: second
  only:
    - develop
  tags:
    - build
  script:
    - echo "Hello world second!"

print_third:
  stage: third

  only:
    - develop

  tags:
    - build
  script:
    - echo "Hello world third!"
